### PR TITLE
additionalArgs were being appended to '/c' instead of this.data.exec for windows.

### PR DESCRIPTION
**Pull request by dwaynehua**

### CODE REVIEW

**Comment by spalger** [comment]
Interesting, I'm not sure how this is supposed to work as I think I just copied it from node core. Do you have any additional info to backup the change?

**Comment by dwaynehua** [comment]
When i was trying to build a project on my windows machine, i got this error: 
```
running cmd.exe with args [ '/s',
  '/c --build_number=1699\n',
  '"grunt --gruntfile=./client/Gruntfile.js"' ]
'--build_number' is not recognized as an internal or external command,
operable program or batch file.
```

as you can see, --build_number is being appended to the /c. It should be getting appended to the "grunt --gruntfile=./client/Gruntfile.js"

On line 94 (in the verison of grunt-run that i'm on) the win32 version has 3 elements in the args array but the other version has only 2.

right below that, additionalArgs is being appended to args[1] no matter what.

**Comment by spalger** [comment]
Works for me, thanks @dwaynehua!

**Comment by dwaynehua** [comment]
no problem!

**Pull request merged**
