### PR TITLE
fix: wait for process to close on stop task

### LINKED ISSUE #18: Second run cannot be stopped
I have got the following configuration and second stop doesn't stop the server, it prints `>> server already stopped`, which is not true.

After some debugging, I found that `clearPid` is invoked by `proc.on('close'` from within `trackBackgroundProc`

grunt-run: 0.5.1
node: 0.10.40
```
run: {
server: {
    args: ['server.js'],
    options: {
      cwd: 'site',
      wait: false,
      quiet: true,
      failOnError: true
    }
  }
}
```

```
  grunt.registerTask('one', function(){grunt.log.ok('First run')});
  grunt.registerTask('two', function(){grunt.log.ok('Second run')});

  grunt.registerTask('myrun', ['env:csa','run:server',
                               'one',
                               'stop:server',
                               'run:server',
                               'two',
                               'stop:server']);
```

### PR DESCRIPTION
**Pull request by yneves**
Fixes #18.

Hello @spalger, would you be so kind to review and merge this?

### CODE REVIEW

**Comment by spalger** [comment]
LGTM, can you move the "stopped" log message into the `closeHandler()` though?

**Comment by yneves** [comment]
Of course, makes sense. Done.

**Comment by yneves** [comment]
@spalger Plan to publish a new release to npm?

**Comment by spalger** [comment]
Yep, thanks for the reminder

**Pull request merged**
